server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:123456789abcdef} 
  expiration-ms: 3600000 # 1 hora

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apprace_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # cria/tabela e atualiza se necessário
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
